### PR TITLE
Optimises build stage for docker image

### PR DESCRIPTION
**Pull request by utkarsh867**
Until now, the whole codebase, including the `src` folder, `node_modules` and so on were being copied from the build environment. This meant even overriding the node-modules generated by the image itself.

##### Why were we doing this all along?
We were doing this because the code was dependent on `schema.graphql` and `prisma.graphql`. So we had to have the `src` folder present in the image.

##### So what has changed?
The `schema.graphql` and `prisma.graphql` are now being copied over to `dist` folder. Moreover, a postbuild has been made to edit some files in-place to change `src` to `dist` because I cannot find a neat way to do this on the internet.

### CODE REVIEW

**Comment by 98sean98** [comment]
Is there no way to copy non `.js / .ts` files by configuring `tsconfig`? The other problem with the imports is `importSchema` method used in `schema.ts` (subsequently `schema.js` in `/dist`) which still refers to `./src/schema.graphql` needs to be changed to `./dist/schema.graphql` to correctly use the newly copied `schema.graphql` file. Based on my understanding, that's what's going on right?

**Comment by utkarsh867** [comment]
> Is there no way to copy non `.js / .ts` files by configuring `tsconfig`? The other problem with the imports is `importSchema` method used in `schema.ts` (subsequently `schema.js` in `/dist`) which still refers to `./src/schema.graphql` needs to be changed to `./dist/schema.graphql` to correctly use the newly copied `schema.graphql` file. Based on my understanding, that's what's going on right?

You got this right!

I have read this somewhere that TypeScript does not ever want to include this feature to be able to copy files into `dist` folder because they believe that there are other ways to do that and they just want to do what they are meant to do, perfectly. I agree with that ideology.

There could be a lot of ways to solve this problem. We could use webpack and babel and so on, but I just decided to take my own approach to it because it would be a lot of overhead to introduce new tools to the build for something so minor.

You are also right about the `importSchema` method used in `schema.ts`. It has a string argument, so typescript does not transform the path. Hence the posbuild.

**Comment by 98sean98** [comment]
I see. I read up on typescript's approach, and arrived at the same conclusion.

I still think `prisma.graphql` as a generated file should live within `./generated` though.

**Comment by utkarsh867** [comment]
> I see. I read up on typescript's approach, and arrived at the same conclusion.
> 
> I still think `prisma.graphql` as a generated file should live within `./generated` though.

Why do you say that? Is there any disadvantages to bringing it outside? or any advantages of keeping it in `generated`?

**Comment by utkarsh867** [comment]
I had my reason for bringing it out, but again I would like to hear yours.

**Comment by 98sean98** [comment]
> > I see. I read up on typescript's approach, and arrived at the same conclusion.
> > I still think `prisma.graphql` as a generated file should live within `./generated` though.
> 
> Why do you say that? Is there any disadvantages to bringing it outside? or any advantages of keeping it in `generated`?

From a developer's perspective, it's a little weird to see `prisma.graphql` living directly under `/src` when this file is not meant to be modified. Basically, I'll be annoyed.

**Comment by utkarsh867** [comment]
I see. Well I’ll encourage you to look at a prisma 2 project structure. There is no generated folder in src

**Comment by utkarsh867** [comment]
Another thing I think I can add is that prisma.graphql is not generated by default. We as developers have decided to generate it because we need it.

**Comment by utkarsh867** [comment]
And it was living under src anyway, just inside generated.

**Comment by utkarsh867** [comment]
@98sean98 I think there are two major elements in the checklist:
- [ ] Docker image works in the cluster in local environment.
- [ ] Be satisfied that the production deployment will work as expected.

**Comment by 98sean98** [comment]
> I see. Well I’ll encourage you to look at a prisma 2 project structure. There is no generated folder in src

Not true for code first graphql approach though, which seems to be better for prisma 2 from what I've read.

Either way, you're right, especially considering the important elements in the checklist.

**Comment by utkarsh867** [comment]
> > I see. Well I’ll encourage you to look at a prisma 2 project structure. There is no generated folder in src
> 
> Not necessarily true for code first graphql approach though, which seems to be better for prisma 2 from what I've read. For example, `nexus` could generate type bindings and graphql files if used.
> 
> Either way, you're right, especially considering the important elements in the checklist.

This is actually quite interesting. I did some playing around with nexus and nexus-prisma yesterday evening. There seem to be some horrible stability issues but the nexus seems quite an amazing way to build graphql apis.

I am not sure if nexus is usable for production environments though? Seems quite flaky to me. I ran into multiple issues where I had to completely delete `node_modules` again and again.

**Comment by 98sean98** [comment]
Totally agree that the whole prisma 2 stack, nexus, etc. are not stable enough for production. Not to mention the lack of documentation as the whole thing is so new, and breaking.

**Comment by utkarsh867** [comment]
Okay, I have actually managed to get the Prisma 2 + Nexus combination to work properly.

In terms of the approach for now, moving the prisma.graphql outside or inside does not matter much. However, if you think this is an issue, I can move it back in. But I think it is completely fine to have it outside.

Please let me know of any other issues. I will wait for you to approve before merging.

**Comment by 98sean98** [comment]
I think we're good.

**Pull request merged**
